### ISSUE TITLE
cf push error.help me.thanks!

### ISSUE THREAD

**Issue by tsxyz** [yudai/cf_nise_installer#126]
root@lishuai-desktop:~/cf_nise_installer/test_app# cf login
API endpoint: https://api.lishuai.local

Email> admin

Password> 
Authenticating...
OK

Targeted org DevBox

Targeted space test

                   
API endpoint:   https://api.lishuai.local (API version: 2.23.0)   
User:           admin   
Org:            DevBox   
Space:          test   

root@lishuai-desktop:~/cf_nise_installer/test_app# cf push
Using manifest file /root/cf_nise_installer/test_app/manifest.yml

Updating app hello in org DevBox / space test as admin...
OK

Using route hello.lishuai.local
Uploading hello...
Uploading app files from: /root/cf_nise_installer/test_app
Uploading 917, 4 files
Done uploading               
OK

Stopping app hello in org DevBox / space test as admin...
OK

Starting app hello in org DevBox / space test as admin...
-----> Downloaded app package (4.0K)
-----> Downloaded app buildpack cache (1.5M)
-------> Buildpack version 1.3.0
-----> Compiling Ruby/Rack
-----> Using Ruby version: ruby-2.0.0
-----> Installing dependencies using 1.7.12
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Using rack 1.5.2
       Using tilt 1.4.1
       Using rack-protection 1.5.0
       Using bundler 1.7.12
       Using sinatra 1.4.3
       Your bundle is complete!
       Gems in the groups development and test were not installed.
       It was installed into ./vendor/bundle
       Bundle completed (0.23s)
       Cleaning up the bundler cache.
###### WARNING:
       You have not declared a Ruby version in your Gemfile.
       To set your Ruby version add this line to your Gemfile:
       ruby '2.0.0'
       # See https://devcenter.heroku.com/articles/ruby-versions for more information.
###### WARNING:
       No Procfile detected, using the default web server (webrick)
       https://devcenter.heroku.com/articles/ruby-default-web-server

-----> Uploading droplet (13M)

FAILED
Server error, status code: 500, error code: 10001, message: An unknown error occurred.

TIP: use 'cf logs hello --recent' for more information

root@lishuai-desktop:~/cf_nise_installer/test_app# cf logs hello --recent
Connected, dumping recent logs for app hello in org DevBox / space test as admin...

2015-04-10T17:26:42.30+0800 [STG/0]      ERR 
2015-04-10T17:26:44.32+0800 [STG/0]      OUT -----> Uploading droplet (13M)
2015-04-10T17:26:46.91+0800 [DEA/0]      OUT Starting app instance (index 0) with guid 6f86fa7b-fe77-41d3-b4a2-c2ddee31a795
2015-04-10T17:26:48.14+0800 [App/0]      ERR [2015-04-10 09:26:48] INFO  WEBrick 1.3.1
2015-04-10T17:26:48.14+0800 [App/0]      ERR [2015-04-10 09:26:48] INFO  ruby 2.0.0 (2014-11-13) [x86_64-linux]
2015-04-10T17:26:48.15+0800 [App/0]      ERR [2015-04-10 09:26:48] INFO  WEBrick::HTTPServer#start: pid=31 port=61003
2015-04-10T18:03:23.86+0800 [API/0]      OUT Updated app with guid 6f86fa7b-fe77-41d3-b4a2-c2ddee31a795 ({"name"=>"hello", "instances"=>1, "memory"=>128, "environment_json"=>"PRIVATE DATA HIDDEN"})
2015-04-10T18:03:29.00+0800 [API/0]      OUT Updated app with guid 6f86fa7b-fe77-41d3-b4a2-c2ddee31a795 ({"state"=>"STOPPED"})
2015-04-10T18:03:29.01+0800 [App/0]      ERR [2015-04-10 10:03:29] FATAL SignalException: SIGTERM
2015-04-10T18:03:29.01+0800 [App/0]      ERR    /home/vcap/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/server.rb:170:in `select'
2015-04-10T18:03:29.01+0800 [App/0]      ERR    /home/vcap/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/server.rb:170:in `block in start'
2015-04-10T18:03:29.01+0800 [App/0]      ERR    /home/vcap/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/server.rb:32:in `start'
2015-04-10T18:03:29.01+0800 [App/0]      ERR    /home/vcap/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/webrick/server.rb:160:in `start'
2015-04-10T18:03:29.01+0800 [App/0]      ERR    /home/vcap/app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/handler/webrick.rb:14:in `run'
2015-04-10T18:03:29.01+0800 [App/0]      ERR    /home/vcap/app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/server.rb:264:in `start'
2015-04-10T18:03:29.01+0800 [App/0]      ERR    /home/vcap/app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/server.rb:141:in `start'
2015-04-10T18:03:29.01+0800 [App/0]      ERR    /home/vcap/app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/bin/rackup:4:in `<top (required)>'
2015-04-10T18:03:29.01+0800 [App/0]      ERR    /home/vcap/app/vendor/bundle/ruby/2.0.0/bin/rackup:23:in `load'
2015-04-10T18:03:29.01+0800 [App/0]      ERR    /home/vcap/app/vendor/bundle/ruby/2.0.0/bin/rackup:23:in `<main>'
2015-04-10T18:03:29.01+0800 [App/0]      ERR [2015-04-10 10:03:29] INFO  going to shutdown ...
2015-04-10T18:03:29.01+0800 [App/0]      ERR [2015-04-10 10:03:29] INFO  WEBrick::HTTPServer#start done.

root@lishuai-desktop:~/cf_nise_installer/test_app# cf apps
Getting apps in org DevBox / space test as admin...
FAILED
Server error, status code: 500, error code: 10001, message: An unknown error occurred.

help me,thank you very much!

**Comment by tsxyz** [comment]
root@lishuai-desktop:~# CF_TRACE=true cf apps

VERSION:
6.10.0-b78bf10

Getting apps in org DevBox / space test as admin...

REQUEST: [2015-04-11T10:05:08+08:00]
GET /v2/spaces/b94b1c28-3983-494b-9ba5-d4626774acc3/summary HTTP/1.1
Host: api.lishuai.local
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.10.0-b78bf10 / linux



RESPONSE: [2015-04-11T10:05:13+08:00]
HTTP/1.1 500 Internal Server Error
Content-Length: 99
Content-Type: application/json;charset=utf-8
Date: Sat, 11 Apr 2015 02:05:13 GMT
Server: nginx
X-Cf-Requestid: 3def92c9-6311-499a-7408-19fc9b60f1ed
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 621402ee-4a08-4b97-66b6-6be8561ee2b2::d5d97ec0-7457-4300-b0a5-a878db26d9f6

{
  "error_code": "UnknownError",
  "description": "An unknown error occurred.",
  "code": 10001
}

FAILED
Server error, status code: 500, error code: 10001, message: An unknown error occurred.
FAILED
Server error, status code: 500, error code: 10001, message: An unknown error occurred.

**Comment by yudai** [comment]
I cannot reproduce the problem on my environment. Could you recreate your devbox and try again?

**Comment by tsxyz** [comment]
Thank you, I try to install the three times, don't have this problem now.
