### ISSUE TITLE
I can't connect with a MySQL User-Provided Service Instances using Node.js

### ISSUE THREAD

**Issue by jabrena** [yudai/cf_nise_installer#132]
Good night,

I have in a Ubuntu system ( Ubuntu 12.04.5 LTS) a Cloud foundry installation using this project. I have deployed without any problem a Node.js application but when I try to connect with MySQL, I can't connect but in localhost I can do it without any problem.

In CF side, I created a service using this syntax:

Syntax: cf cups SERVICE_INSTANCE -p "host, port, dbname, username, password"
Example: cf cups mySQLService -p "host, port, dbname, username, password"
localhost
3206
demo
root
xxyyzz

later, I have updated the manifest file to bind the service.

Note: The Mysql server was installed in the same machine.

What is the problem?

``` shell
cf logs NodeJSHelloWorld --recent
Connected, dumping recent logs for app NodeJSHelloWorld in org DevBox / space de
v as admin...

2015-07-20T11:56:48.24+0200 [STG/0]      OUT -----> Uploading droplet (10M)
2015-07-20T11:56:52.82+0200 [DEA/0]      OUT Starting app instance (index 0) wit
h guid 788a28be-2aea-40e4-baf3-3d2347e94415
2015-07-20T11:56:54.24+0200 [App/0]      OUT     Detected 1024 MB available memo
ry, 512 MB limit per process (WEB_MEMORY)
2015-07-20T11:56:54.24+0200 [App/0]      OUT Recommending WEB_CONCURRENCY=2
2015-07-20T11:56:54.32+0200 [App/0]      OUT Server running at http://127.0.0.1:
8000/
2015-07-20T12:01:42.60+0200 [RTR/0]      OUT nodejshelloworld.37.48.81.170.xip.i
o - [20/07/2015:12:01:42 +0200] "GET / HTTP/1.1" 200 12 "-" "Mozilla/5.0 (Window
s NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 x vca
p_request_id:152ad987-5fc9-4bd1-73fd-2b7b1bab0707 response_time:0.010714236 app_
id:788a28be-2aea-40e4-baf3-3d2347e94415
2015-07-20T12:01:42.67+0200 [RTR/0]      OUT nodejshelloworld.37.48.81.170.xip.i
o - [20/07/2015:12:01:42 +0200] "GET /favicon.ico HTTP/1.1" 200 12 "http://nodej
shelloworld.xxx.xip.io/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK
it/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36" x vcap_request_id:04e30c2d-2258
-4d42-6c1c-7107917b6c03 response_time:0.003492407 app_id:788a28be-2aea-40e4-baf3
-3d2347e94415
2015-07-20T12:46:21.92+0200 [API/0]      OUT Updated app with guid 788a28be-2aea
-40e4-baf3-3d2347e94415 ({"name"=>"NodeJSHelloWorld", "command"=>"PRIVATE DATA H
IDDEN", "instances"=>1, "memory"=>64, "buildpack"=>"https://github.com/cloudfoun
dry/nodejs-buildpack", "environment_json"=>"PRIVATE DATA HIDDEN"})
2015-07-20T12:46:31.77+0200 [API/0]      OUT Updated app with guid 788a28be-2aea
-40e4-baf3-3d2347e94415 ({"state"=>"STOPPED"})
2015-07-20T12:46:31.80+0200 [App/0]      ERR
2015-07-20T12:46:32.54+0200 [DEA/0]      OUT Got staging request for app with id
 788a28be-2aea-40e4-baf3-3d2347e94415
2015-07-20T12:46:32.82+0200 [DEA/0]      OUT Stopping app instance (index 0) wit
h guid 788a28be-2aea-40e4-baf3-3d2347e94415
2015-07-20T12:46:32.82+0200 [DEA/0]      OUT Stopped app instance (index 0) with
 guid 788a28be-2aea-40e4-baf3-3d2347e94415
2015-07-20T12:46:33.69+0200 [API/0]      OUT Updated app with guid 788a28be-2aea
-40e4-baf3-3d2347e94415 ({"state"=>"STARTED"})
2015-07-20T12:46:33.78+0200 [STG/0]      OUT -----> Downloaded app package (348K
)
2015-07-20T12:46:33.84+0200 [STG/0]      OUT -----> Downloaded app buildpack cac
he (280K)
2015-07-20T12:46:34.13+0200 [STG/0]      ERR     Cloning into '/tmp/buildpacks/n
odejs-buildpack'...
2015-07-20T12:46:36.72+0200 [STG/0]      OUT     Submodule 'compile-extensions'
(https://github.com/cloudfoundry-incubator/compile-extensions.git) registered fo
r path 'compile-extensions'
2015-07-20T12:46:36.74+0200 [STG/0]      ERR Cloning into 'compile-extensions'..
.
2015-07-20T12:46:38.07+0200 [STG/0]      OUT Submodule path 'compile-extensions'
: checked out 'ce9345a9a6e7b00266194cadd18dbef37e791a7b'
2015-07-20T12:46:38.11+0200 [STG/0]      OUT -------> Buildpack version 1.4.2
2015-07-20T12:46:38.12+0200 [STG/0]      OUT -----> Creating runtime environment

2015-07-20T12:46:38.13+0200 [STG/0]      OUT        NPM_CONFIG_LOGLEVEL=error
2015-07-20T12:46:38.13+0200 [STG/0]      OUT        NPM_CONFIG_PRODUCTION=true
2015-07-20T12:46:38.13+0200 [STG/0]      OUT        NODE_MODULES_CACHE=true
2015-07-20T12:46:38.13+0200 [STG/0]      OUT -----> Installing binaries
2015-07-20T12:46:38.14+0200 [STG/0]      OUT        engines.node (package.json):
  0.12.x
2015-07-20T12:46:38.14+0200 [STG/0]      OUT        engines.npm (package.json):
  unspecified (use default)
2015-07-20T12:46:38.14+0200 [STG/0]      OUT        Resolving node version 0.12.
x via semver.io...
2015-07-20T12:46:38.69+0200 [STG/0]      OUT        Downloading and installing n
ode 0.12.7...
2015-07-20T12:46:41.33+0200 [STG/0]      OUT        Using default npm version: 2
.11.3
2015-07-20T12:46:41.55+0200 [STG/0]      OUT -----> Restoring cache
2015-07-20T12:46:41.77+0200 [STG/0]      OUT        Loading 1 from cacheDirector
ies (default):
2015-07-20T12:46:41.77+0200 [STG/0]      OUT        - node_modules (exists - ski
pping)
2015-07-20T12:46:41.77+0200 [STG/0]      OUT -----> Building dependencies
2015-07-20T12:46:41.77+0200 [STG/0]      OUT        Prebuild detected (node_modu
les already exists)
2015-07-20T12:46:41.77+0200 [STG/0]      OUT        Rebuilding any native module
s
2015-07-20T12:46:42.32+0200 [STG/0]      OUT        bluebird@2.9.34 /tmp/staged/
app/node_modules/bluebird
2015-07-20T12:46:42.32+0200 [STG/0]      OUT        mysql@2.8.0 /tmp/staged/app/
node_modules/mysql
2015-07-20T12:46:42.32+0200 [STG/0]      OUT        bignumber.js@2.0.7 /tmp/stag
ed/app/node_modules/mysql/node_modules/bignumber.js
2015-07-20T12:46:42.32+0200 [STG/0]      OUT        readable-stream@1.1.13 /tmp/
staged/app/node_modules/mysql/node_modules/readable-stream
2015-07-20T12:46:42.32+0200 [STG/0]      OUT        core-util-is@1.0.1 /tmp/stag
ed/app/node_modules/mysql/node_modules/readable-stream/node_modules/core-util-is

2015-07-20T12:46:42.32+0200 [STG/0]      OUT        isarray@0.0.1 /tmp/staged/ap
p/node_modules/mysql/node_modules/readable-stream/node_modules/isarray
2015-07-20T12:46:42.32+0200 [STG/0]      OUT        string_decoder@0.10.31 /tmp/
staged/app/node_modules/mysql/node_modules/readable-stream/node_modules/string_d
ecoder
2015-07-20T12:46:42.32+0200 [STG/0]      OUT        inherits@2.0.1 /tmp/staged/a
pp/node_modules/mysql/node_modules/readable-stream/node_modules/inherits
2015-07-20T12:46:42.33+0200 [STG/0]      OUT        Installing any new modules (
package.json)
2015-07-20T12:46:42.91+0200 [STG/0]      OUT -----> Caching build
2015-07-20T12:46:42.92+0200 [STG/0]      OUT        Clearing previous node cache

2015-07-20T12:46:42.94+0200 [STG/0]      OUT        Saving 1 cacheDirectories (d
efault):
2015-07-20T12:46:42.94+0200 [STG/0]      OUT        - node_modules
2015-07-20T12:46:42.96+0200 [STG/0]      OUT -----> Build succeeded!
2015-07-20T12:46:43.44+0200 [STG/0]      OUT        ├── bluebird@2.9.34
2015-07-20T12:46:43.44+0200 [STG/0]      OUT        └── mysql@2.8.0
2015-07-20T12:46:45.06+0200 [STG/0]      OUT -----> Uploading droplet (10M)
2015-07-20T12:46:49.73+0200 [DEA/0]      OUT Starting app instance (index 0) wit
h guid 788a28be-2aea-40e4-baf3-3d2347e94415
2015-07-20T12:46:51.08+0200 [App/0]      OUT     Detected 1024 MB available memo
ry, 512 MB limit per process (WEB_MEMORY)
2015-07-20T12:46:51.08+0200 [App/0]      OUT Recommending WEB_CONCURRENCY=2
2015-07-20T12:46:51.21+0200 [App/0]      OUT Server running at http://127.0.0.1:
8000/
2015-07-20T12:47:26.58+0200 [RTR/0]      OUT nodejshelloworld.37.48.81.170.xip.i
o - [20/07/2015:12:47:26 +0200] "GET / HTTP/1.1" 200 17 "-" "Mozilla/5.0 (Window
s NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Saf
x x_forwarded_for:"" vca
p_request_id:14d12060-6a02-48ad-7fb7-71ec0f6ecd15 response_time:0.077577165 app_
id:788a28be-2aea-40e4-baf3-3d2347e94415
2015-07-20T12:47:26.59+0200 [App/0]      ERR     Unhandled rejection Error: conn
ect ECONNREFUSED
2015-07-20T12:47:26.59+0200 [App/0]      ERR     at exports._errnoException (uti
l.js:746:11)
2015-07-20T12:47:26.59+0200 [App/0]      ERR     at TCPConnectWrap.afterConnect
[as oncomplete] (net.js:1010:19)
2015-07-20T12:47:26.59+0200 [App/0]      ERR     --------------------
2015-07-20T12:47:26.59+0200 [App/0]      ERR     at Protocol._enqueue (/home/vca
p/app/node_modules/mysql/lib/protocol/Protocol.js:135:48)
2015-07-20T12:47:26.59+0200 [App/0]      ERR     at Protocol.handshake (/home/vc
ap/app/node_modules/mysql/lib/protocol/Protocol.js:52:41)
2015-07-20T12:47:26.59+0200 [App/0]      ERR     at Connection.connect (/home/vc
ap/app/node_modules/mysql/lib/Connection.js:123:18)
2015-07-20T12:47:26.59+0200 [App/0]      ERR     at Connection._implyConnect (/h
ome/vcap/app/node_modules/mysql/lib/Connection.js:415:10)
2015-07-20T12:47:26.59+0200 [App/0]      ERR     at Connection.query (/home/vcap
/app/node_modules/mysql/lib/Connection.js:199:8)
2015-07-20T12:47:26.59+0200 [App/0]      ERR     at Connection.tryCatcher (/home
/vcap/app/node_modules/bluebird/js/main/util.js:26:23)
2015-07-20T12:47:26.59+0200 [App/0]      ERR     at ret (eval at <anonymous> (/h
ome/vcap/app/node_modules/bluebird/js/main/promisify.js:163:12), <anonymous>:14:
23)
2015-07-20T12:47:26.59+0200 [App/0]      ERR     at Server.<anonymous> (/home/vc
ap/app/app2.js:22:52)
2015-07-20T12:47:26.59+0200 [App/0]      ERR     at Server.emit (events.js:110:1
7)
2015-07-20T12:47:26.59+0200 [App/0]      ERR     at HTTPParser.parserOnIncoming
(_http_server.js:491:12)
2015-07-20T12:47:26.59+0200 [App/0]      ERR     at HTTPParser.parserOnHeadersCo
mplete (_http_common.js:111:23)
2015-07-20T12:47:26.59+0200 [App/0]      ERR     at Socket.socketOnData (_http_s
erver.js:343:22)
2015-07-20T12:47:26.59+0200 [App/0]      ERR     at Socket.emit (events.js:107:1
7)
2015-07-20T12:47:26.59+0200 [App/0]      ERR     at readableAddChunk (_stream_re
adable.js:163:16)
2015-07-20T12:47:26.59+0200 [App/0]      ERR     at Socket.Readable.push (_strea
m_readable.js:126:10)
2015-07-20T12:47:26.59+0200 [App/0]      ERR     at TCP.onread (net.js:538:20)
2015-07-20T12:47:26.65+0200 [RTR/0]      OUT nodejshelloworld.37.48.81.170.xip.i
o - [20/07/2015:12:47:26 +0200] "GET /favicon.ico HTTP/1.1" 200 17 "http://nodej
shelloworld.37.48.81.170.xip.io/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK
it/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36" 37.48.81.170:4
7611 x_forwarded_for:"62.14.228.196, 37.48.81.170" vcap_request_id:7dc146d1-3645
-4062-5e50-83b311703d44 response_time:0.007367812 app_id:788a28be-2aea-40e4-baf3
-3d2347e94415
2015-07-20T12:47:26.65+0200 [App/0]      ERR Unhandled rejection Error: connect
ECONNREFUSED
2015-07-20T12:47:26.65+0200 [App/0]      ERR     at exports._errnoException (uti
l.js:746:11)
2015-07-20T12:47:26.65+0200 [App/0]      ERR     at TCPConnectWrap.afterConnect
[as oncomplete] (net.js:1010:19)
2015-07-20T12:47:26.65+0200 [App/0]      ERR     --------------------
2015-07-20T12:47:26.65+0200 [App/0]      ERR     at Protocol._enqueue (/home/vca
p/app/node_modules/mysql/lib/protocol/Protocol.js:135:48)
2015-07-20T12:47:26.65+0200 [App/0]      ERR     at Protocol.handshake (/home/vc
ap/app/node_modules/mysql/lib/protocol/Protocol.js:52:41)
2015-07-20T12:47:26.65+0200 [App/0]      ERR     at Connection.connect (/home/vc
ap/app/node_modules/mysql/lib/Connection.js:123:18)
2015-07-20T12:47:26.65+0200 [App/0]      ERR     at Connection._implyConnect (/h
ome/vcap/app/node_modules/mysql/lib/Connection.js:415:10)
2015-07-20T12:47:26.65+0200 [App/0]      ERR     at Connection.query (/home/vcap
/app/node_modules/mysql/lib/Connection.js:199:8)
2015-07-20T12:47:26.65+0200 [App/0]      ERR     at Connection.tryCatcher (/home
/vcap/app/node_modules/bluebird/js/main/util.js:26:23)
2015-07-20T12:47:26.65+0200 [App/0]      ERR     at ret (eval at <anonymous> (/h
ome/vcap/app/node_modules/bluebird/js/main/promisify.js:163:12), <anonymous>:14:
23)
2015-07-20T12:47:26.65+0200 [App/0]      ERR     at Server.<anonymous> (/home/vc
ap/app/app2.js:22:52)
2015-07-20T12:47:26.65+0200 [App/0]      ERR     at Server.emit (events.js:110:1
7)
2015-07-20T12:47:26.65+0200 [App/0]      ERR     at HTTPParser.parserOnIncoming
(_http_server.js:491:12)
2015-07-20T12:47:26.65+0200 [App/0]      ERR     at HTTPParser.parserOnHeadersCo
mplete (_http_common.js:111:23)
2015-07-20T12:47:26.65+0200 [App/0]      ERR     at Socket.socketOnData (_http_s
erver.js:343:22)
2015-07-20T12:47:26.65+0200 [App/0]      ERR     at Socket.emit (events.js:107:1
7)
2015-07-20T12:47:26.65+0200 [App/0]      ERR     at readableAddChunk (_stream_re
adable.js:163:16)
2015-07-20T12:47:26.65+0200 [App/0]      ERR     at Socket.Readable.push (_strea
m_readable.js:126:10)
2015-07-20T12:47:26.65+0200 [App/0]      ERR     at TCP.onread (net.js:538:20)

```

Many thanks in advance.

Juan Antonio

**Comment by jabrena** [comment]
The problem was not located in CF instance. MySQL service must be installed in another host.
Besides, it is necessary to configurate MySQL to accept remote request.
